### ISSUE TITLE
Association Users - Fonctions - Applications

### ISSUE THREAD

**Issue by DarylNoupik** [DarylNoupik/habilitationSG#1]
# Prerequisites

J'ai les images suivantes pour mettre dans le contexte 

# Images

## Utilisateurs 

![image](https://user-images.githubusercontent.com/49377133/232820906-09ece240-8370-43db-844c-ed8a800513b1.png)
 J'ai les utilisateurs suivants avec leurs fonctions

## Fonctions 
![image](https://user-images.githubusercontent.com/49377133/232823335-82277508-8c79-4d86-a13a-59183f842134.png)

les fonctions sont associés avec les applications 

# Contexte 

Une fois les relations crées étant donné que les utilisateurs avait été créé au préalable lorsque on les associe une fonction ils doivent hériter des applications attachées à la fonction et de meme pour le faire on devrait pouvoir récupérer les nouvelles applications nouvellement attacher à une fonction.
# Pistes de solutions

J'ai a cet effet pensé a crée un observateur pour observer les utilisateurs et les fonctions pour palier à ce probleme mais je rencontre des erreurs

**Comment by DarylNoupik** [comment]
Le champ 0 correspond aux nombres d'applications sur la partie Users @Sizer123

**Comment by Sizer123** [comment]
OK. Je vais checker ton problème avec les observers. Mais comme je te disais. Laravel ne détecte pas les événements. C'est urgent ?

**Comment by DarylNoupik** [comment]
Oui quand même,! Merci d'avance, mais Lorsque je supprime l'observer est actif

**Comment by Sizer123** [comment]
Il faut tester avec l'évènement creating pour voir.

**Comment by DarylNoupik** [comment]
Okay , j'ai essayé avec l'evenement created comme dans a vue dans le user observer  ca a marcher mes ca cree une sorte de duplicata

**Comment by Sizer123** [comment]
Avec l'évènement **created** ou **creating** ?

**Comment by Sizer123** [comment]
Par

> Avec l'évènement **created** ou **creating** ?

Parce que l'évènement **created** est appelé après l'évènement **creating**.

**Comment by DarylNoupik** [comment]
avec l'évènement created

**Comment by Sizer123** [comment]
Et tu as pu résoudre le soucis de duplicata dont tu parlais ?

**Comment by DarylNoupik** [comment]
non pas encore , depuis la j'ai pas pu m'asseoir depuis ! Mais je crois que c'est entre l'observer et le fonctionscontroler

**Comment by Sizer123** [comment]
Tu as gardé la propriété dispatchEvents dans le model ?

**Comment by DarylNoupik** [comment]
non , le has event permet de prevenir cela

**Comment by Sizer123** [comment]
Tu as une idée de la raison pour laquelle l'observer ne fonctionnait pas au départ ?

**Comment by DarylNoupik** [comment]
une chose bête me faire croire que c'est parce que j'avais mis dans le App Provider au lieu du Even Provider mais  bon

**Comment by DarylNoupik** [comment]
EventProvider

**Comment by Sizer123** [comment]
OK.

**Comment by DarylNoupik** [comment]
![image](https://user-images.githubusercontent.com/49377133/233133345-6ce7c228-f72a-4a30-990d-ed79e1031bca.png)

bon comme je disais c'est à cause de eventserviceprovider

**Comment by DarylNoupik** [comment]
Alternative solution
